# Generated by Django 4.2 on 2023-05-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_products',
            name='fkCupboard',
        ),
        migrations.AddField(
            model_name='t_article',
            name='fkCupboard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_cupboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_article',
            name='fkProduct',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_article',
            name='fkRoom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_categories',
            name='fkType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_cupboard',
            name='fkRoom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_room'),
            preserve_default=False,
        ),
    ]
