# Generated by Django 4.2 on 2023-05-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestock', '0003_remove_t_categories_fktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_products',
            name='fkArticle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_article'),
        ),
    ]
