# Generated by Django 4.2 on 2023-05-26 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestock', '0004_alter_t_products_fkarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_borrow',
            name='fkArticle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_article'),
            preserve_default=False,
        ),
    ]
