# Generated by Django 4.2 on 2023-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestock', '0005_t_borrow_fkarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_article',
            name='artName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='t_categories',
            name='catName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='t_cupboard',
            name='cupName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='t_products',
            name='proName',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='t_room',
            name='rooName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='t_types',
            name='typName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
