# Generated by Django 4.2 on 2023-06-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestock', '0006_alter_t_article_artname_alter_t_categories_catname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_products',
            name='proImage',
            field=models.ImageField(blank=True, null=True, upload_to='proImages'),
        ),
    ]
