# Generated by Django 4.2 on 2023-06-07 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestock', '0007_alter_t_products_proimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_article',
            name='fkCupboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_cupboard'),
        ),
        migrations.AlterField(
            model_name='t_products',
            name='fkArticle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestock.t_article'),
        ),
    ]
